name: LocalStack TypeDB Extension Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  LOCALSTACK_DISABLE_EVENTS: "1"
  LOCALSTACK_AUTH_TOKEN: ${{ secrets.TEST_LOCALSTACK_AUTH_TOKEN }}

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LocalStack and extension
        run: |
          docker pull localstack/localstack-pro &
          docker pull typedb/typedb &

          pip install localstack
          localstack extensions install "git+https://github.com/whummer/localstack-utils.git#egg=localstack-typedb&subdirectory=localstack-typedb"

          DEBUG=1 localstack start -d
          localstack wait

      - name: Run integration tests
        run: |
          make install
          make test
          make test-lambda

      - name: Print logs
        if: always()
        run: |
          localstack logs
          localstack stop
